### ISSUE TITLE
players question

### ISSUE THREAD

**Issue by SPCcleveland9035** [TheLittleDoc/GameMaster#9]
in the json file, i saw an area for players, how does that work? I couldnt find any documentation on it. sorry if i am wasting your time

**Comment by TheLittleDoc** [comment]
Hi there! Thanks for reaching out! At this time, GameMaster is winding down and we're shifting over toward a new application I contributed to, [TeleScore](https://github.com/JumpShot-Interactive/TeleScore). Unfortunately, I don't think that I'll be getting around to buttoning up the last few unfinished features in GameMaster, but most of what I'd promised and more is available in TeleScore today. I'll have to double check where we're at on the players features. 

Should I finish it here in GameMaster, it would allow you to temporarily push to a file a specific player's name and stats based on a roster you can define/upload. You can take that text file, like all the others, and link it to a text object in OBS. I never worked out entirely how it would be implemented, but we'll see if the interest is there to finish it up. In the meantime, check out TeleScore and see if it meets your needs. Cheers!

[https://github.com/JumpShot-Interactive/TeleScore](https://github.com/JumpShot-Interactive/TeleScore)
